<footer>
    <div class="col-md-12 text-center">
        <a href='http://wiki.kumbiaphp.com/Team_Development_KumbiaPHP_Framework'>© 2007 - <?= date('Y')?> KumbiaPHP Team</a>
        
    </div>
    <div class="col-md-12 text-center"> <?= 'Ejecutado en ', round((microtime(1) - $_SERVER['REQUEST_TIME_FLOAT'])*1000, 4), ' ms. usando ', number_format(memory_get_usage() / 1048576, 3), ' MB de memoria'?></div>
</footer>
