<?php View::partial('backend/admin_menu'); ?>

<?php echo Form::open()?>

  <div class="form-group">
    <label><h4>Tweet <small>140 caracteres</small></h4></label>
    <?php echo Form::textarea('tweet.cuerpo',array('class'=>'form-control','rows'=>'3','maxlength'=>'140')) ?>
  </div>

  <div class="form-group">
    <label><h4>Tags <small>Opcional</small></h4></label>
    <?php echo Form::text('tweet.tags',array('class'=>'form-control')) ?>
  </div>

  <div class="form-group">
    <label><h4>URL <small>Opcional</small></h4</label>
    <?php echo Form::text('tweet.url',array('class'=>'form-control')) ?>
  </div>

<?php echo Form::submit('Agregar', array('class'=>'btn btn-primary btn-lg btn-block')) ?>

<?php echo Form::close()?>