<?php View::partial('backend/admin_menu'); ?>

<?php echo Form::open()?>

    <div class="form-group">
        <label><h4>Campo</h4></label>
        <?php echo Form::text('configuracion.campo',array('class'=>'form-control','disabled'=>'disabled')) ?>
    </div>

    <div class="form-group">
        <label><h4>Valor</h4></label>
        <?php echo Form::textarea('configuracion.valor',array('class'=>'form-control','rows'=>'3')) ?>
    </div>

<?php echo Form::submit('Actualizar', array('class'=>'btn btn-primary btn-lg btn-block')) ?>

<?php echo Form::close()?>

