<?php View::partial('backend/admin_menu'); ?>

<table class="table table-hover table-condensed table-responsive">
    <thead>
        <tr>
            <th class="col-hidden">CAMPO</th>
            <th class="col-hidden">VALOR</th>
            <th class="col-blocked text-center">ACCIONES</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($configuracion as $item):?>
        <tr>
            <td><?php echo $item->campo ?></td>
            <td><?php echo $item->valor ?></td>
            <td class="text-right"><?php echo Html::link("admin/configuracion_editar/$item->id","<i class='fa fa-edit'></i>",array('class'=>'btn btn-sm btn-success')) ?></td>
        </tr>  
    <?php endforeach; ?>
    </tbody>
</table>