<div class="row login">
    <div class="col-md-4 col-md-offset-4">
        <?php echo Form::open() ?>
        <?php echo Form::text('login',array('class'=>'form-control'))?>
        <?php echo Form::password('password',array('class'=>'form-control'))?>
        <?php echo Form::submit('Iniciar sesion',array('class'=>'btn btn-primary btn-lg btn-block')) ?>
        <?php echo Form::close() ?>
    </div>
</div>     