<!DOCTYPE html>
<html lang="es">
 <head>
  <meta charset=<?= APP_CHARSET ?> >
  <title><?php echo $title?></title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <?php Tag::css('bootstrap.min') ?>
  <?php Tag::css('style') ?>
  <?php Tag::css('font-awesome.min') ?>
  <?= Html::includeCss() ?>
</head>
<body>
<div class="container">
  <header class="row">
      <div class="col-md-8">
        <?= Html::img('kumbiaphp.svg', 'KumbiaPHP logo') ?>
      </div>
      <div class="col-md-4 text-right">
          App: <strong><?= basename(dirname(APP_PATH)) ?></strong> (<?= PRODUCTION ? 'Production' : 'Development' ?>)
      </div>
  </header>
  <?php View::content() ?>
  <?php View::partial('kumbia/footer') ?>
</div>
</body>
  <?php echo Tag::js('jquery-1.12.4.min') ?>
  <?php echo Tag::js('bootstrap') ?>

</html>
